buckley = Dog.create(name:"Buckley", age: 2, size:"Medium", kids_compatible: true, pets_compatible: true, image_url: "https://scontent-ort2-1.xx.fbcdn.net/v/t1.0-9/45788068_10156992831794548_4199652127636717568_o.jpg?_nc_cat=108&_nc_oc=AQmpEtPBkfk1NZfpFcH5bcSp079aNl16PPw4gqJHuuBhsWmoK7vxWRb0zU9gvCo7GeM&_nc_ht=scontent-ort2-1.xx&oh=b8d086ffbabc48d2e950a9f1b1c0d138&oe=5D5862CD", fixed: true, vaccinated: true, bio: "He's wiggly!")
snoopy = Dog.create(name: "Snoopy", age: 4, size: "Small", kids_compatible: true, pets_compatible: false, image_url: "https://images-na.ssl-images-amazon.com/images/I/61OHZivMu1L._SY550_.jpg", fixed: true, vaccinated: true, bio: "He's grumpy!")
muttley = Dog.create(name: "Muttley", age: 3, size: "Medium", kids_compatible: false, pets_compatible: true, image_url: "https://i.pinimg.com/236x/80/62/6b/80626b8f3d6d372d4eb5809ef32a5a34--cartoon-dog-cartoon-characters.jpg", fixed: false, vaccinated: false, bio: "He's goofy!")
pluto = Dog.create(name: "Pluto", age: 1, size: "Large", kids_compatible: false, pets_compatible: false, image_url: "http://astrologynewsservice.com/wp-content/uploads/2014/08/1240-305x260.png", fixed: false, vaccinated: true, bio: "He's sneaky!")
scooby = Dog.create(name: "Scooby", age: 2, size: "Large", kids_compatible: true, pets_compatible: true, image_url: "https://i.pinimg.com/originals/91/5a/ed/915aeddee3f1a6cb2ceb2c48f4bd9974.jpg", fixed: true, vaccinated: true, bio: "He's faint-hearted!")
odie = Dog.create(name: "Odie", age: 5, size: "Small", kids_compatible: true, pets_compatible: false, image_url: "https://i.pinimg.com/originals/16/e6/3d/16e63de1de47d3a0331c7e76ba28a232.jpg", fixed: true, vaccinated: false, bio: "He's mischevious!")
droopy = Dog.create(name: "Droopy", age: 1, size: "Medium", kids_compatible: true, pets_compatible: true, image_url: "https://upload.wikimedia.org/wikipedia/en/f/fd/Droopy_dog.png", fixed: true, vaccinated: false, bio: "He's sleepy!")
toby = Dog.create(name: "Toby", age: 8, size: "Small", kids_compatible: false, pets_compatible: true, image_url: "https://image.freepik.com/free-vector/cartoon-dog-zombie_61878-274.jpg", fixed: true, vaccinated: true, bio: "He's undead!")

sam = Owner.create(name: "Sam")
lisa = Owner.create(name: "Lisa")

bart = Trainer.create(name: "Bart", bio: "Friendly", available_on_weekends: true)
marge = Trainer.create(name: "Marge", bio: "Smart", available_on_weekends: false)
jeff = Trainer.create(name: "Jeff", bio: "Experienced", available_on_weekends: true)

lab = Breed.create(name: "Labrador Retriever", size: "Medium", temperament: "Friendly", life_expectancy: "12 years", description: "Energetic")
pitbull = Breed.create(name: "American Pitbull Terrier", size: "Large", temperament: "Loyal", life_expectancy: "10 years", description: "Strong")
beagle = Breed.create(name: "Beagle", size: "Small", temperament: "Timid", life_expectancy: "14 years", description: "Digger")
hound = Breed.create(name: "Bloodhound", size: "Large", temperament: "Confident", life_expectancy: "15 years", description: "Sniffer")
corgi = Breed.create(name: "Welsh Corgi", size: "Small", temperament: "Playful", life_expectancy: "14 years", description: "Herder")

DogBreed.create(dog: buckley, breed: lab)
DogBreed.create(dog: buckley, breed: pitbull)
DogBreed.create(dog: snoopy, breed: beagle)
DogBreed.create(dog: muttley, breed: lab)
DogBreed.create(dog: pluto, breed: hound)
DogBreed.create(dog: scooby, breed: hound)
DogBreed.create(dog: scooby, breed: lab)
DogBreed.create(dog: odie, breed: corgi)
DogBreed.create(dog: droopy, breed: lab)
DogBreed.create(dog: droopy, breed: hound)
DogBreed.create(dog: toby, breed: pitbull)
